#pragma once

#define AUTHORS_A "Lukas Knöpfle"
#define AUTHORS_B "Lukas Knöpfle"
#define AUTHORS_C "Johannes Pfanger"
#define AUTHORS_D "Johannes Pfanger"
#define AUTHORS_E "Luis Bierbrauer"
#define AUTHORS_F "Luis Bierbrauer"
#define AUTHORS_G ""
#define AUTHORS_H ""
#define AUTHORS_I ""
#define AUTHORS_J ""
#define AUTHORS_K ""
#define AUTHORS_L ""
#define AUTHORS_M ""
#define AUTHORS_N ""
