#pragma once

#define AUTHORS_A "Lukas Knöpfle"
#define AUTHORS_B "Lukas Knöpfle"
#define AUTHORS_C "Johannes Pfanger"
#define AUTHORS_D "Johannes Pfanger"
#define AUTHORS_E "Luis Bierbrauer"
#define AUTHORS_F "Luis Bierbrauer"
#define AUTHORS_G "Lukas Knöpfle"
#define AUTHORS_H "Lukas Knöpfle"
#define AUTHORS_I "Johannes Pfanger"
#define AUTHORS_J "Johannes Pfanger"
#define AUTHORS_K "Luis Bierbrauer"
#define AUTHORS_L "Luis Bierbrauer"
#define AUTHORS_M "Lukas Knöpfle"
#define AUTHORS_N "Lukas Knöpfle"
